# Generated by Django 5.2.5 on 2025-08-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentmethod_alter_order_payment_method'),
        ('users', '0003_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='aaja aaja mere ghar aaja'),
            preserve_default=False,
        ),
    ]
