# Generated by Django 5.2.5 on 2025-08-08 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, help_text='6-digit one-time password', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
