# Generated by Django 5.2.5 on 2025-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otprequest_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
