# Generated by Django 5.2.5 on 2025-08-08 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_otprequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
