# Generated by Django 5.2.5 on 2025-08-17 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='otprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(help_text='Phone number including country code (optional).', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='otp',
            field=models.CharField(help_text='6-digit OTP code.', max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='phone_number',
            field=models.CharField(help_text='Enter the phone number associated with the OTP.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter a 10-digit phone number.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='idx_address_user'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='idx_address_city'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone_number'], name='idx_otp_phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='idx_user_phone'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='otprequest',
            table='otp_request',
        ),
    ]
