# Generated by Django 5.2.5 on 2025-08-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_address_options_alter_otprequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
