# Generated by Django 5.2.5 on 2025-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
