# Generated by Django 5.2.5 on 2025-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_featured_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
