# Generated by Django 5.2.5 on 2025-08-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_weight_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_per_unit',
            field=models.PositiveIntegerField(default=100, help_text='Defines how much quantity (in unit) the price refers to. e.g. 100 g, 500 ml, 1 pcs.'),
        ),
    ]
