# Generated by Django 5.2.5 on 2025-08-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_quantity_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_per_unit',
        ),
    ]
