# Generated by Django 5.2.5 on 2025-08-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_quantity_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.PositiveIntegerField(),
        ),
    ]
