# Generated by Django 5.2.5 on 2025-08-17 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='product',
            name='google_file_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
