# Generated by Django 5.2.5 on 2025-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_featured_image_product_google_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='google_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
