# Generated by Django 5.2.5 on 2025-08-25 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_url',
            new_name='image_file_id',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
