# Generated by Django 5.2.5 on 2025-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_image_url_banner_image_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_file_id',
        ),
        migrations.AddField(
            model_name='banner',
            name='google_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
