# Generated by Django 5.2.5 on 2025-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_banner_image_file_id_banner_google_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product')], default='category', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='min_discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Show only products with at least this discount % (leave empty if not applicable)', null=True),
        ),
    ]
