# Generated by Django 5.2.5 on 2025-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_banner_banner_type_banner_min_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='min_discount_percentage',
        ),
        migrations.AddField(
            model_name='banner',
            name='search_query',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
