# Generated by Django 5.2.5 on 2025-08-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
